### ISSUE TITLE
"Forgot Password" no funciona en ciclope

### ISSUE THREAD

**Issue by oscarfonts** [geomatico/dataportal#38]
Reportado por Jordi Sorribas.

**Comment by michogar** [comment]
He el dataportal que yo tengo en local el proceso funciona perfectamente. Si miramos el log en ciclope, parece que da problemas el usuario de gmail de la cuenta. Adjunto exception:

Username and Password not accepted. Learn more at  
535 5.7.1 http://support.google.com/mail/bin/answer.py?answer=14257 q7sm2290393wix.5

```
at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:809)
at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:752)
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:669)
at javax.mail.Service.connect(Service.java:317)
at javax.mail.Service.connect(Service.java:176)
at javax.mail.Service.connect(Service.java:125)
at javax.mail.Transport.send0(Transport.java:194)
at javax.mail.Transport.send(Transport.java:124)
at org.dataportal.datasources.Mail.send(Mail.java:57)
at org.dataportal.datasources.Mail.send(Mail.java:83)
at org.dataportal.LoginServlet.doPost(LoginServlet.java:106)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
at java.lang.Thread.run(Thread.java:662)
```

**Comment by michogar** [comment]
La pass del usuario icos.dataportal era erronea. Modificado en el dataportal.properties y funcionando
